"""Backfill reconstructors package.

Exports the ``Candidate`` dataclass and convenience aliases for the four
parse functions so callers can do::

    from telemetry.tools.reconstructors import (
        Candidate,
        parse_existing_rows,
        parse_log,
        git_windows_for_adventure,
        parse_task_logs,
    )
"""

from __future__ import annotations

import dataclasses


@dataclasses.dataclass(frozen=True)
class Candidate:
    """A telemetry candidate extracted by one of the four reconstructors.

    Mirrors the shape of ``MetricsRow`` from ``schema.py`` plus two extra
    fields (``confidence`` and ``source``) that record where the data came
    from and how reliable it is.  Run ID is intentionally left empty ("") at
    this stage; the merge step (T012) assigns stable IDs.
    """

    run_id: str          # 12-hex or "" (generated by merge)
    timestamp: str       # ISO-8601 UTC, or "" when unavailable
    agent: str
    task: str            # task ID or "-"
    model: str
    tokens_in: int
    tokens_out: int
    duration_s: int
    turns: int
    cost: float
    result: str
    confidence: str      # "medium" | "low" | "estimated"  (never "high")
    source: str          # "existing" | "log" | "git" | "task_log"


# Convenience re-exports so the full parse interface is available from the
# package root without callers needing to import sub-modules directly.
from .existing_rows import parse as parse_existing_rows          # noqa: E402
from .log_parser import parse as parse_log                       # noqa: E402
from .git_windows import for_adventure as git_windows_for_adventure  # noqa: E402
from .task_logs import parse as parse_task_logs                  # noqa: E402

__all__ = [
    "Candidate",
    "parse_existing_rows",
    "parse_log",
    "git_windows_for_adventure",
    "parse_task_logs",
]
