//! ark-verify — AST → SMT-LIB2 text translator (smtlib_text backend).
//!
//! Walks an `ArkFile`, emitting a complete `.smt2` program that can be fed
//! to the external `z3` CLI. No linking to libz3 / z3-sys.

pub use ark_dsl;

use ark_dsl::{ArkFile, Constraint, DataField, EntityDef, Expr, Item, TypeExpr};

use std::fmt::Write as _;

/// Public entry point: translate an entire `ArkFile` into an SMT-LIB2 program.
pub fn to_smtlib(file: &ArkFile) -> String {
    let mut out = String::new();
    out.push_str("; Generated by ark-verify (smtlib_text backend)\n");
    out.push_str("(set-logic QF_LRA)\n");

    // Pass 1: declarations + range asserts for every entity's $data fields.
    for item in &file.items {
        if let Some(entity) = item_as_entity(item) {
            emit_declarations(&mut out, entity);
        }
    }

    // Pass 2: invariant checks.
    for item in &file.items {
        if let Some(entity) = item_as_entity(item) {
            emit_invariants(&mut out, entity);
        }
    }

    out.push_str("(exit)\n");
    out
}

/// Extract an `EntityDef` reference from a `Class` or `Abstraction` item.
fn item_as_entity(item: &Item) -> Option<&EntityDef> {
    match item {
        Item::Class(e) | Item::Abstraction(e) => Some(e),
        _ => None,
    }
}

/// Emit `(declare-const ...)` and `(assert (and ...))` for every $data field.
fn emit_declarations(out: &mut String, entity: &EntityDef) {
    if entity.data_fields.is_empty() {
        return;
    }
    let _ = writeln!(out, "; data fields from {}", entity.name);
    for field in &entity.data_fields {
        emit_field_decl(out, &entity.name, field);
    }
}

fn emit_field_decl(out: &mut String, entity_name: &str, field: &DataField) {
    let sort = type_to_sort(&field.ty);
    let qualified = namespaced(entity_name, &field.name);
    let _ = writeln!(out, "(declare-const {qualified} {sort})");
    if let Some(constraint) = &field.constraint {
        if let Some(assertion) = constraint_to_assert(&qualified, sort, constraint, entity_name) {
            let _ = writeln!(out, "{assertion}");
        }
    }
}

/// Emit invariant assertions wrapped in `(push 1) ... (pop 1)` per entity.
fn emit_invariants(out: &mut String, entity: &EntityDef) {
    if entity.invariants.is_empty() {
        return;
    }
    let _ = writeln!(out, "; invariant from {}", entity.name);
    for inv in &entity.invariants {
        let body = expr_to_smt(inv, &entity.name);
        out.push_str("(push 1)\n");
        let _ = writeln!(out, "(assert (not {body}))");
        out.push_str("(check-sat)\n");
        out.push_str("(pop 1)\n");
    }
}

/// Map an ARK `TypeExpr` to an SMT-LIB2 sort string.
fn type_to_sort(ty: &TypeExpr) -> &'static str {
    match ty {
        TypeExpr::Named(name) => match name.as_str() {
            "Int" | "i8" | "i16" | "i32" | "i64" | "u8" | "u16" | "u32" | "u64" | "usize" => "Int",
            "Float" | "f32" | "f64" | "Real" => "Real",
            "Bool" | "bool" => "Bool",
            _ => "Real",
        },
        // Generics/arrays are not numeric; default to Real so the script stays valid.
        TypeExpr::Generic(_, _) | TypeExpr::Array(_, _) => "Real",
    }
}

/// Build a namespaced identifier: `Vehicle_fuel`.
fn namespaced(entity: &str, field: &str) -> String {
    format!("{entity}_{field}")
}

/// Translate a `Constraint` into a single `(assert ...)` line, or `None` if skipped.
fn constraint_to_assert(
    qualified: &str,
    sort: &'static str,
    constraint: &Constraint,
    entity: &str,
) -> Option<String> {
    match constraint {
        Constraint::Range(lo, hi) => {
            let lo_s = number_literal(lo, sort).unwrap_or_else(|| expr_to_smt(lo, entity));
            let hi_s = number_literal(hi, sort).unwrap_or_else(|| expr_to_smt(hi, entity));
            Some(format!(
                "(assert (and (>= {qualified} {lo_s}) (<= {qualified} {hi_s})))"
            ))
        }
        Constraint::EnumSet(values) => {
            if values.is_empty() {
                return None;
            }
            let disjuncts: Vec<String> = values
                .iter()
                .map(|v| {
                    let lit = number_literal(v, sort).unwrap_or_else(|| expr_to_smt(v, entity));
                    format!("(= {qualified} {lit})")
                })
                .collect();
            Some(format!("(assert (or {}))", disjuncts.join(" ")))
        }
    }
}

/// If this expression is a `Number`, format it as an Int or Real literal
/// according to `sort`. Returns None for non-numbers.
fn number_literal(expr: &Expr, sort: &'static str) -> Option<String> {
    if let Expr::Number(n) = expr {
        Some(format_number(*n, sort))
    } else {
        None
    }
}

fn format_number(n: f64, sort: &'static str) -> String {
    if sort == "Int" && n.fract() == 0.0 && n.is_finite() {
        format!("{}", n as i64)
    } else if n.fract() == 0.0 && n.is_finite() {
        format!("{:.1}", n)
    } else {
        format!("{}", n)
    }
}

/// Translate an ARK `Expr` into an SMT-LIB2 S-expression string.
pub fn expr_to_smt(expr: &Expr, entity: &str) -> String {
    match expr {
        Expr::Number(n) => {
            if n.fract() == 0.0 && n.is_finite() {
                // Default numeric literal: emit as Real (`1.0`) to stay safe in QF_LRA.
                format!("{:.1}", n)
            } else {
                format!("{}", n)
            }
        }
        Expr::Bool(b) => if *b { "true" } else { "false" }.to_string(),
        Expr::Ident(name) => namespaced(entity, name),
        Expr::BinOp(lhs, op, rhs) => {
            let l = expr_to_smt(lhs, entity);
            let r = expr_to_smt(rhs, entity);
            let smt_op = map_binop(op);
            if op == "!=" {
                format!("(distinct {l} {r})")
            } else {
                format!("({smt_op} {l} {r})")
            }
        }
        Expr::UnaryOp(op, inner) => {
            let x = expr_to_smt(inner, entity);
            match op.as_str() {
                "not" | "!" => format!("(not {x})"),
                "-" => format!("(- {x})"),
                other => format!("; TODO: unsupported unary op {other}\ntrue"),
            }
        }
        Expr::FnCall(_, _) => "true ; TODO: unsupported FnCall".to_string(),
        Expr::ForAll { .. } => "true ; TODO: unsupported ForAll".to_string(),
        Expr::DottedPath(_) => "true ; TODO: unsupported DottedPath".to_string(),
        Expr::StringLit(_) => "true ; TODO: unsupported StringLit".to_string(),
        Expr::Pipe { .. } => "true ; TODO: unsupported Pipe".to_string(),
        Expr::ParamRef { .. } => "true ; TODO: unsupported ParamRef".to_string(),
    }
}

fn map_binop(op: &str) -> &'static str {
    match op {
        "+" => "+",
        "-" => "-",
        "*" => "*",
        "/" => "/",
        ">=" => ">=",
        "<=" => "<=",
        ">" => ">",
        "<" => "<",
        "==" | "=" => "=",
        "!=" => "distinct",
        "and" | "&&" => "and",
        "or" | "||" => "or",
        _ => "=",
    }
}

// ============================================================
// Tests
// ============================================================

#[cfg(test)]
mod tests {
    use super::*;
    use ark_dsl::{Constraint, DataField, EntityDef, Expr, Item, TypeExpr};

    fn minimal_vehicle() -> ArkFile {
        let fuel = DataField {
            name: "fuel".into(),
            ty: TypeExpr::Named("Float".into()),
            constraint: Some(Constraint::Range(Expr::Number(0.0), Expr::Number(100.0))),
            default: None,
        };
        let priority = DataField {
            name: "priority".into(),
            ty: TypeExpr::Named("Int".into()),
            constraint: Some(Constraint::Range(Expr::Number(1.0), Expr::Number(10.0))),
            default: None,
        };
        // invariant: fuel >= 0
        let inv = Expr::BinOp(
            Box::new(Expr::Ident("fuel".into())),
            ">=".into(),
            Box::new(Expr::Number(0.0)),
        );
        let entity = EntityDef {
            name: "Vehicle".into(),
            inherits: vec![],
            data_fields: vec![fuel, priority],
            in_ports: vec![],
            out_ports: vec![],
            processes: vec![],
            invariants: vec![inv],
            temporals: vec![],
            description: None,
        };
        ArkFile {
            imports: vec![],
            items: vec![Item::Class(entity)],
            ..Default::default()
        }
    }

    #[test]
    fn translates_minimal_class() {
        let file = minimal_vehicle();
        let smt = to_smtlib(&file);
        assert!(smt.contains("(set-logic QF_LRA)"));
        assert!(smt.contains("(declare-const Vehicle_fuel Real)"));
        assert!(smt.contains("(declare-const Vehicle_priority Int)"));
        assert!(smt.contains("(assert (and (>= Vehicle_fuel 0.0) (<= Vehicle_fuel 100.0)))"));
        assert!(smt.contains("(assert (and (>= Vehicle_priority 1) (<= Vehicle_priority 10)))"));
        assert!(smt.contains("; invariant from Vehicle"));
        assert!(smt.contains("(push 1)"));
        assert!(smt.contains("(assert (not (>= Vehicle_fuel 0.0)))"));
        assert!(smt.contains("(check-sat)"));
        assert!(smt.contains("(pop 1)"));
        assert!(smt.trim_end().ends_with("(exit)"));
    }

    #[test]
    fn binop_and_unary_translate() {
        let expr = Expr::BinOp(
            Box::new(Expr::UnaryOp("not".into(), Box::new(Expr::Bool(false)))),
            "and".into(),
            Box::new(Expr::BinOp(
                Box::new(Expr::Ident("x".into())),
                "!=".into(),
                Box::new(Expr::Number(2.0)),
            )),
        );
        let s = expr_to_smt(&expr, "E");
        assert_eq!(s, "(and (not false) (distinct E_x 2.0))");
    }
}
