//! ark-codegen — AST → Rust source translator.
//!
//! Ports a minimal slice of `tools/codegen/ark_codegen.py` to Rust: entity →
//! AoS struct + optional `impl Default` / `new()` generated from $data field
//! defaults. The SoA batch machinery and process-body generation are out of
//! scope for this slice.

pub use ark_dsl;

use ark_dsl::{ArkFile, DataField, EntityDef, Expr, Item, TypeExpr};

use std::fmt::Write as _;

/// Header emitted at the top of a generated file.
const FILE_HEADER: &str = "// Generated by ark-codegen. Do not edit.\n";

/// Translate an entire `ArkFile` to a single Rust source string.
///
/// Walks every `Item::Class` / `Item::Abstraction` and concatenates each
/// entity's `gen_rust_entity` output. Other item kinds are ignored for now.
pub fn gen_rust_file(file: &ArkFile) -> String {
    let mut out = String::from(FILE_HEADER);
    for item in &file.items {
        if let Some(entity) = item_as_entity(item) {
            out.push('\n');
            out.push_str(&gen_rust_entity(entity));
        }
    }
    out
}

/// Extract a borrowed `EntityDef` from `Class` / `Abstraction` items.
fn item_as_entity(item: &Item) -> Option<&EntityDef> {
    match item {
        Item::Class(e) | Item::Abstraction(e) => Some(e),
        _ => None,
    }
}

/// Produce the Rust source for a single entity: struct + optional `new()` /
/// `Default` impls.
pub fn gen_rust_entity(entity: &EntityDef) -> String {
    let mut out = String::new();
    let name = &entity.name;
    let has_defaults = entity.data_fields.iter().any(|f| f.default.is_some());

    // Derive list — drop `Default` when we emit our own `impl Default` to
    // avoid duplicate definitions.
    if has_defaults {
        out.push_str("#[derive(Debug, Clone)]\n");
    } else {
        out.push_str("#[derive(Debug, Clone, Default)]\n");
    }
    let _ = writeln!(out, "pub struct {name} {{");
    for field in &entity.data_fields {
        let rtype = type_to_rust(&field.ty);
        let _ = writeln!(out, "    pub {}: {},", field.name, rtype);
    }
    out.push_str("}\n");

    if has_defaults {
        out.push('\n');
        let _ = writeln!(out, "impl {name} {{");
        out.push_str("    /// Construct with spec defaults. Generated from ARK $data defaults.\n");
        out.push_str("    #[inline]\n");
        out.push_str("    pub fn new() -> Self {\n");
        out.push_str("        Self {\n");
        for field in &entity.data_fields {
            let val = field_default_value(field);
            let _ = writeln!(out, "            {}: {},", field.name, val);
        }
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("}\n");
        out.push('\n');
        let _ = writeln!(out, "impl Default for {name} {{");
        out.push_str("    #[inline]\n");
        out.push_str("    fn default() -> Self { Self::new() }\n");
        out.push_str("}\n");
    }

    out
}

/// Compute the per-field numeric suffix (`f32` vs `i32`) for literal
/// defaults so they compile without coercion warnings.
fn field_num_suffix(field: &DataField) -> &'static str {
    match &field.ty {
        TypeExpr::Named(name) => match name.as_str() {
            "Int" | "i8" | "i16" | "i32" | "i64" | "u8" | "u16" | "u32" | "u64" | "usize" => "i32",
            _ => "f32",
        },
        _ => "f32",
    }
}

/// Produce the RHS used for a field inside the generated `new()` body.
fn field_default_value(field: &DataField) -> String {
    match &field.default {
        Some(expr) => {
            let suffix = field_num_suffix(field);
            expr_to_rust(expr, suffix)
        }
        None => "Default::default()".to_string(),
    }
}

/// Map an ARK `TypeExpr` to a Rust type string. Unknown named types fall
/// back to `String` as a placeholder (matching the Python codegen).
pub fn type_to_rust(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Named(name) => match name.as_str() {
            "Float" => "f32".to_string(),
            "Int" => "i32".to_string(),
            "Bool" => "bool".to_string(),
            "String" => "String".to_string(),
            _ => "String".to_string(),
        },
        TypeExpr::Generic(_, _) | TypeExpr::Array(_, _) => "String".to_string(),
    }
}

/// Translate a minimal subset of ARK expressions to Rust source.
///
/// Handles `Number`, `Bool`, `Ident`, and `BinOp`. Everything else is stubbed
/// out with a `Default::default()` fallback plus a `/* unsupported */`
/// comment — callers are expected to keep expressions trivial for now.
pub fn expr_to_rust(expr: &Expr, num_suffix: &str) -> String {
    match expr {
        Expr::Number(n) => format_number_literal(*n, num_suffix),
        Expr::Bool(b) => if *b { "true" } else { "false" }.to_string(),
        Expr::Ident(name) => name.trim_end_matches('\'').to_string(),
        Expr::BinOp(lhs, op, rhs) => {
            let l = expr_to_rust(lhs, num_suffix);
            let r = expr_to_rust(rhs, num_suffix);
            format!("({l} {op} {r})")
        }
        Expr::UnaryOp(op, inner) => {
            let x = expr_to_rust(inner, num_suffix);
            match op.as_str() {
                "not" | "!" => format!("(!{x})"),
                "-" => format!("(-{x})"),
                _ => "/* unsupported */ Default::default()".to_string(),
            }
        }
        Expr::StringLit(_)
        | Expr::DottedPath(_)
        | Expr::FnCall(_, _)
        | Expr::ForAll { .. } => "/* unsupported */ Default::default()".to_string(),
    }
}

/// Format a numeric literal with the given suffix. Integers get an integer
/// rendering (`0_i32`), fractional values keep their fractional form
/// (`0.5_f32`). Whole-number floats become `0_f32`.
fn format_number_literal(n: f64, suffix: &str) -> String {
    if suffix.starts_with('i') || suffix.starts_with('u') {
        if n.is_finite() && n.fract() == 0.0 {
            return format!("{}_{}", n as i64, suffix);
        }
        return format!("{n}_{suffix}");
    }
    if n.is_finite() && n.fract() == 0.0 {
        format!("{}_{}", n as i64, suffix)
    } else {
        format!("{n}_{suffix}")
    }
}

// ============================================================
// Tests
// ============================================================

#[cfg(test)]
mod tests {
    use super::*;
    use ark_dsl::{
        ArkFile, Constraint, DataField, EntityDef, Expr, Item, RegistryDef, TypeExpr,
    };

    fn empty_entity(name: &str) -> EntityDef {
        EntityDef {
            name: name.into(),
            inherits: vec![],
            data_fields: vec![],
            in_ports: vec![],
            out_ports: vec![],
            processes: vec![],
            invariants: vec![],
            temporals: vec![],
            description: None,
        }
    }

    fn float_field(name: &str, default: Option<f64>, range: Option<(f64, f64)>) -> DataField {
        DataField {
            name: name.into(),
            ty: TypeExpr::Named("Float".into()),
            constraint: range.map(|(lo, hi)| {
                Constraint::Range(Expr::Number(lo), Expr::Number(hi))
            }),
            default: default.map(Expr::Number),
        }
    }

    #[test]
    fn renders_simple_class() {
        let mut entity = empty_entity("Vehicle");
        entity.data_fields.push(float_field("speed", Some(0.0), None));
        let src = gen_rust_entity(&entity);
        assert!(src.contains("pub struct Vehicle"), "struct header: {src}");
        assert!(src.contains("pub fn new()"), "new fn: {src}");
        assert!(src.contains("speed: 0_f32"), "literal default: {src}");
        assert!(src.contains("impl Default for Vehicle"), "default impl: {src}");
        // With a default, `Default` must be dropped from the derive list.
        assert!(
            src.contains("#[derive(Debug, Clone)]"),
            "derive without Default: {src}"
        );
        assert!(
            !src.contains("#[derive(Debug, Clone, Default)]"),
            "derive should drop Default: {src}"
        );
    }

    #[test]
    fn renders_class_without_defaults() {
        let mut entity = empty_entity("Sensor");
        entity.data_fields.push(float_field("temp", None, Some((0.0, 100.0))));
        let src = gen_rust_entity(&entity);
        assert!(
            src.contains("#[derive(Debug, Clone, Default)]"),
            "Default must be in derive: {src}"
        );
        assert!(!src.contains("impl Default for Sensor"), "no manual impl: {src}");
        assert!(!src.contains("pub fn new()"), "no new(): {src}");
        assert!(src.contains("pub temp: f32"), "field present: {src}");
    }

    #[test]
    fn gen_rust_file_skips_non_entity() {
        let mut entity = empty_entity("Widget");
        entity.data_fields.push(float_field("mass", None, None));
        let registry = RegistryDef {
            name: "Systems".into(),
            entries: vec![],
        };
        let file = ArkFile {
            imports: vec![],
            items: vec![Item::Class(entity), Item::Registry(registry)],
            ..Default::default()
        };
        let src = gen_rust_file(&file);
        assert!(src.starts_with("// Generated by ark-codegen"), "header: {src}");
        assert!(src.contains("pub struct Widget"), "class rendered: {src}");
        assert!(!src.contains("Systems"), "registry name leaked: {src}");
        assert!(!src.contains("Registry"), "registry kind leaked: {src}");
    }

    #[test]
    fn type_mapping_defaults_are_correct() {
        assert_eq!(type_to_rust(&TypeExpr::Named("Float".into())), "f32");
        assert_eq!(type_to_rust(&TypeExpr::Named("Int".into())), "i32");
        assert_eq!(type_to_rust(&TypeExpr::Named("Bool".into())), "bool");
        assert_eq!(type_to_rust(&TypeExpr::Named("String".into())), "String");
        assert_eq!(type_to_rust(&TypeExpr::Named("Quaternion".into())), "String");
    }

    #[test]
    fn expr_to_rust_handles_basics() {
        assert_eq!(expr_to_rust(&Expr::Number(1.5), "f32"), "1.5_f32");
        assert_eq!(expr_to_rust(&Expr::Number(2.0), "f32"), "2_f32");
        assert_eq!(expr_to_rust(&Expr::Number(3.0), "i32"), "3_i32");
        assert_eq!(expr_to_rust(&Expr::Bool(true), "f32"), "true");
        assert_eq!(expr_to_rust(&Expr::Ident("x".into()), "f32"), "x");
        let bin = Expr::BinOp(
            Box::new(Expr::Ident("a".into())),
            "+".into(),
            Box::new(Expr::Number(1.0)),
        );
        assert_eq!(expr_to_rust(&bin, "f32"), "(a + 1_f32)");
    }
}
